services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      MONGO_URL: ${MONGO_URL}
    restart: unless-stopped
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped 